// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TabMessage } from "./TabMessage";

/**
 * What an outside process may send. Separate from `MercuryEvent` so a wire frame cannot be a key or a quit.
 */
export type IncomingEvent = { "kind": "IncomingEvent.Tab", "value": TabMessage };
